apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-env
  template:
    metadata:
      labels:
        app: dev-env
    spec:
      containers:
      - name: dev
        image: docker.io/helenfrank/dev-env:latest
        securityContext:
          privileged: true
